#!/usr/bin/env perl
use strict;
use Plack::Runner;
use Hydra;

require Getopt::Long;
Getopt::Long::Configure("no_ignore_case", "no_auto_abbrev", "pass_through");

my @argv = @ARGV;

my $runner = Plack::Runner->new(server => 'Starman', env => 'deployment');
$runner->parse_options(@argv);

if ($runner->{loader} eq 'Restarter') {
    warn <<WARN;
!!
!! Using restarter with -r or -R options is known to cause issues with process supervisor
!! such as start_server, and it is STRONGLY discouraged to use with Starman. You have been warned.
!!
WARN
}

$runner->set_options(argv => \@argv);
my $app = Hydra->psgi_app();
$runner->run($app);
